# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ungdungbanhang.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 110, 521, 191))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.full_name = QtWidgets.QLabel(self.groupBox)
        self.full_name.setGeometry(QtCore.QRect(60, 50, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.full_name.setFont(font)
        self.full_name.setObjectName("full_name")
        self.date_buy_2 = QtWidgets.QLabel(self.groupBox)
        self.date_buy_2.setGeometry(QtCore.QRect(60, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.date_buy_2.setFont(font)
        self.date_buy_2.setObjectName("date_buy_2")
        self.full_name_1 = QtWidgets.QLineEdit(self.groupBox)
        self.full_name_1.setGeometry(QtCore.QRect(200, 60, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.full_name_1.setFont(font)
        self.full_name_1.setObjectName("full_name_1")
        self.date_buy = QtWidgets.QLineEdit(self.groupBox)
        self.date_buy.setGeometry(QtCore.QRect(200, 109, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date_buy.setFont(font)
        self.date_buy.setText("")
        self.date_buy.setObjectName("date_buy")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 491, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 320, 611, 371))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 90, 181, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 166, 457))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rauma_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rauma_edit.setFont(font)
        self.rauma_edit.setObjectName("rauma_edit")
        self.verticalLayout.addWidget(self.rauma_edit)
        self.rauma_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.rauma_box.setObjectName("rauma_box")
        self.verticalLayout.addWidget(self.rauma_box)
        self.nuoccam_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nuoccam_edit.setFont(font)
        self.nuoccam_edit.setObjectName("nuoccam_edit")
        self.verticalLayout.addWidget(self.nuoccam_edit)
        self.nuocam_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.nuocam_box.setObjectName("nuocam_box")
        self.verticalLayout.addWidget(self.nuocam_box)
        self.sinhto_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sinhto_edit.setFont(font)
        self.sinhto_edit.setObjectName("sinhto_edit")
        self.verticalLayout.addWidget(self.sinhto_edit)
        self.sinhto_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.sinhto_box.setObjectName("sinhto_box")
        self.verticalLayout.addWidget(self.sinhto_box)
        self.trasua_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.trasua_edit.setFont(font)
        self.trasua_edit.setObjectName("trasua_edit")
        self.verticalLayout.addWidget(self.trasua_edit)
        self.trasua_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.trasua_box.setObjectName("trasua_box")
        self.verticalLayout.addWidget(self.trasua_box)
        self.soda_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.soda_edit.setFont(font)
        self.soda_edit.setObjectName("soda_edit")
        self.verticalLayout.addWidget(self.soda_edit)
        self.soda_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.soda_box.setObjectName("soda_box")
        self.verticalLayout.addWidget(self.soda_box)
        self.tradao_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tradao_edit.setFont(font)
        self.tradao_edit.setObjectName("tradao_edit")
        self.verticalLayout.addWidget(self.tradao_edit)
        self.tradao_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.tradao_box.setObjectName("tradao_box")
        self.verticalLayout.addWidget(self.tradao_box)
        self.tradau_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tradau_edit.setFont(font)
        self.tradau_edit.setObjectName("tradau_edit")
        self.verticalLayout.addWidget(self.tradau_edit)
        self.tradau_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.tradau_box.setObjectName("tradau_box")
        self.verticalLayout.addWidget(self.tradau_box)
        self.tanglua_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tanglua_edit.setFont(font)
        self.tanglua_edit.setObjectName("tanglua_edit")
        self.verticalLayout.addWidget(self.tanglua_edit)
        self.tangluc_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.tangluc_box.setObjectName("tangluc_box")
        self.verticalLayout.addWidget(self.tangluc_box)
        self.trachanh_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.trachanh_edit.setFont(font)
        self.trachanh_edit.setObjectName("trachanh_edit")
        self.verticalLayout.addWidget(self.trachanh_edit)
        self.trachanh_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.trachanh_box.setObjectName("trachanh_box")
        self.verticalLayout.addWidget(self.trachanh_box)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(210, 90, 191, 251))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -60, 176, 457))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.duiga_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.duiga_edit.setFont(font)
        self.duiga_edit.setObjectName("duiga_edit")
        self.verticalLayout_2.addWidget(self.duiga_edit)
        self.duiga_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.duiga_box.setObjectName("duiga_box")
        self.verticalLayout_2.addWidget(self.duiga_box)
        self.bo_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bo_edit.setFont(font)
        self.bo_edit.setObjectName("bo_edit")
        self.verticalLayout_2.addWidget(self.bo_edit)
        self.bo_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.bo_box.setObjectName("bo_box")
        self.verticalLayout_2.addWidget(self.bo_box)
        self.thit_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.thit_edit.setFont(font)
        self.thit_edit.setObjectName("thit_edit")
        self.verticalLayout_2.addWidget(self.thit_edit)
        self.thit_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.thit_box.setObjectName("thit_box")
        self.verticalLayout_2.addWidget(self.thit_box)
        self.ca_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ca_edit.setFont(font)
        self.ca_edit.setObjectName("ca_edit")
        self.verticalLayout_2.addWidget(self.ca_edit)
        self.ca_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.ca_box.setObjectName("ca_box")
        self.verticalLayout_2.addWidget(self.ca_box)
        self.tom_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tom_edit.setFont(font)
        self.tom_edit.setObjectName("tom_edit")
        self.verticalLayout_2.addWidget(self.tom_edit)
        self.tom_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.tom_box.setObjectName("tom_box")
        self.verticalLayout_2.addWidget(self.tom_box)
        self.muc_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.muc_edit.setFont(font)
        self.muc_edit.setObjectName("muc_edit")
        self.verticalLayout_2.addWidget(self.muc_edit)
        self.muc_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.muc_box.setObjectName("muc_box")
        self.verticalLayout_2.addWidget(self.muc_box)
        self.canuong_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.canuong_edit.setFont(font)
        self.canuong_edit.setObjectName("canuong_edit")
        self.verticalLayout_2.addWidget(self.canuong_edit)
        self.canuong_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.canuong_box.setObjectName("canuong_box")
        self.verticalLayout_2.addWidget(self.canuong_box)
        self.xucxich_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.xucxich_edit.setFont(font)
        self.xucxich_edit.setObjectName("xucxich_edit")
        self.verticalLayout_2.addWidget(self.xucxich_edit)
        self.xucxich_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.xucxich_box.setObjectName("xucxich_box")
        self.verticalLayout_2.addWidget(self.xucxich_box)
        self.ghe_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ghe_edit.setFont(font)
        self.ghe_edit.setObjectName("ghe_edit")
        self.verticalLayout_2.addWidget(self.ghe_edit)
        self.tao_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.tao_box.setObjectName("tao_box")
        self.verticalLayout_2.addWidget(self.tao_box)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(420, 90, 181, 251))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 166, 409))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.xoai_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.xoai_edit.setFont(font)
        self.xoai_edit.setObjectName("xoai_edit")
        self.verticalLayout_3.addWidget(self.xoai_edit)
        self.xoai_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.xoai_box.setObjectName("xoai_box")
        self.verticalLayout_3.addWidget(self.xoai_box)
        self.duahau_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.duahau_edit.setFont(font)
        self.duahau_edit.setObjectName("duahau_edit")
        self.verticalLayout_3.addWidget(self.duahau_edit)
        self.duahau_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.duahau_box.setObjectName("duahau_box")
        self.verticalLayout_3.addWidget(self.duahau_box)
        self.khe_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.khe_edit.setFont(font)
        self.khe_edit.setObjectName("khe_edit")
        self.verticalLayout_3.addWidget(self.khe_edit)
        self.khe_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.khe_box.setObjectName("khe_box")
        self.verticalLayout_3.addWidget(self.khe_box)
        self.cam_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cam_edit.setFont(font)
        self.cam_edit.setObjectName("cam_edit")
        self.verticalLayout_3.addWidget(self.cam_edit)
        self.cam_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.cam_box.setObjectName("cam_box")
        self.verticalLayout_3.addWidget(self.cam_box)
        self.tao_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tao_edit.setFont(font)
        self.tao_edit.setObjectName("tao_edit")
        self.verticalLayout_3.addWidget(self.tao_edit)
        self.ghe_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.ghe_box.setObjectName("ghe_box")
        self.verticalLayout_3.addWidget(self.ghe_box)
        self.dao_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dao_edit.setFont(font)
        self.dao_edit.setObjectName("dao_edit")
        self.verticalLayout_3.addWidget(self.dao_edit)
        self.dao_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.dao_box.setObjectName("dao_box")
        self.verticalLayout_3.addWidget(self.dao_box)
        self.dau_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dau_edit.setFont(font)
        self.dau_edit.setObjectName("dau_edit")
        self.verticalLayout_3.addWidget(self.dau_edit)
        self.dau_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.dau_box.setObjectName("dau_box")
        self.verticalLayout_3.addWidget(self.dau_box)
        self.man_edit = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.man_edit.setFont(font)
        self.man_edit.setObjectName("man_edit")
        self.verticalLayout_3.addWidget(self.man_edit)
        self.man_box = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.man_box.setObjectName("man_box")
        self.verticalLayout_3.addWidget(self.man_box)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(10, 30, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(210, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(420, 30, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.vnd_edit = QtWidgets.QLabel(self.centralwidget)
        self.vnd_edit.setGeometry(QtCore.QRect(460, 710, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.vnd_edit.setFont(font)
        self.vnd_edit.setObjectName("vnd_edit")
        self.total_edit = QtWidgets.QPushButton(self.centralwidget)
        self.total_edit.setGeometry(QtCore.QRect(110, 710, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.total_edit.setFont(font)
        self.total_edit.setObjectName("total_edit")
        self.thanhtien_box = QtWidgets.QLineEdit(self.centralwidget)
        self.thanhtien_box.setGeometry(QtCore.QRect(270, 710, 181, 31))
        self.thanhtien_box.setObjectName("thanhtien_box")
        self.hoadon_edit = QtWidgets.QPushButton(self.centralwidget)
        self.hoadon_edit.setGeometry(QtCore.QRect(270, 760, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.hoadon_edit.setFont(font)
        self.hoadon_edit.setObjectName("hoadon_edit")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")   
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #event
        self.total_edit.clicked.connect(self.calcTotal)
        #event
        self.hoadon_edit.clicked.connect(self.invoice)
       
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Thông tin khách hàng"))
        self.full_name.setText(_translate("MainWindow", "Họ và tên"))
        self.date_buy_2.setText(_translate("MainWindow", "Ngày mua"))
        self.label.setText(_translate("MainWindow", "BILL SOFTWARE "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Dịch Vụ"))
        self.rauma_edit.setText(_translate("MainWindow", "Rau má"))
        self.nuoccam_edit.setText(_translate("MainWindow", "Nước cam"))
        self.sinhto_edit.setText(_translate("MainWindow", "Sinh tố"))
        self.trasua_edit.setText(_translate("MainWindow", "Trà sữa"))
        self.soda_edit.setText(_translate("MainWindow", "SODA"))
        self.tradao_edit.setText(_translate("MainWindow", "Trà đào"))
        self.tradau_edit.setText(_translate("MainWindow", "Trà dâu"))
        self.tanglua_edit.setText(_translate("MainWindow", "Tăng lực"))
        self.trachanh_edit.setText(_translate("MainWindow", "Trà chanh"))
        self.duiga_edit.setText(_translate("MainWindow", "Đùi gà"))
        self.bo_edit.setText(_translate("MainWindow", "Bò Bít Tết"))
        self.thit_edit.setText(_translate("MainWindow", "Thịt nướng"))
        self.ca_edit.setText(_translate("MainWindow", "Cá viên"))
        self.tom_edit.setText(_translate("MainWindow", "Tôm "))
        self.muc_edit.setText(_translate("MainWindow", "Mực xào"))
        self.canuong_edit.setText(_translate("MainWindow", "Cá nướng"))
        self.xucxich_edit.setText(_translate("MainWindow", "Xúc xích nướng"))
        self.ghe_edit.setText(_translate("MainWindow", "Ghẹ nướng"))
        self.xoai_edit.setText(_translate("MainWindow", "Xoài"))
        self.duahau_edit.setText(_translate("MainWindow", "Dưa hấu"))
        self.khe_edit.setText(_translate("MainWindow", "Khế"))
        self.cam_edit.setText(_translate("MainWindow", "Cam"))
        self.tao_edit.setText(_translate("MainWindow", "Táo"))
        self.dao_edit.setText(_translate("MainWindow", "Đào"))
        self.dau_edit.setText(_translate("MainWindow", "Dâu"))
        self.man_edit.setText(_translate("MainWindow", "Mận"))
        self.label_33.setText(_translate("MainWindow", "Đồ uống"))
        self.label_34.setText(_translate("MainWindow", "Đồ ăn"))
        self.label_35.setText(_translate("MainWindow", "Trái cây"))
        self.vnd_edit.setText(_translate("MainWindow", "VNĐ"))
        self.total_edit.setText(_translate("MainWindow", "Thành tiền"))
        self.hoadon_edit.setText(_translate("MainWindow", "Xuất hóa đơn"))
        
    def calcTotal(self):
        prices = {
            "rauma_edit": 15000,
            "nuoccam_edit": 10000,
            "sinhto_edit": 30000,
            "trasua_edit": 15000,
            "soda_edit": 20000,
            "tradao_edit": 25000,
            "tradau_edit": 30000,
            "tangluc_edit": 15000,
            "trachanh_edit": 20000,
            "duiga_edit": 50000,
            "bo_edit": 300000,
            "thit_edit": 200000,
            "ca_edit": 90000,
            "tom_edit": 20000,
            "muc_edit": 500000,
            "canuong_edit": 150000,
            "xucxich_edit": 170000,
            "ghe_edit": 200000,
            "xoai_edit": 20000,
            "duahau_edit": 30000,
            "khe_edit": 10000,
            "cam_edit": 20000,
            "tao_edit": 15000,
            "dao_edit": 20000,
            "dau_edit": 50000,
            "man_edit": 20000,
        } 
        sum = (False)\
            + int(self.rauma_box.text()) * prices["rauma_edit"] \
            + int(self.nuocam_box.text()) * prices["nuoccam_edit"]\
            + int(self.sinhto_box.text()) * prices["sinhto_edit"] \
            + int(self.trasua_box.text()) * prices["trasua_edit"]\
            + int(self.soda_box.text()) * prices["soda_edit"] \
            + int(self.tradao_box.text()) * prices["tradao_edit"]\
            + int(self.tradau_box.text()) * prices["tradau_edit"] \
            + int(self.tangluc_box.text()) * prices["tangluc_edit"]\
            + int(self.trachanh_box.text()) * prices["trachanh_edit"] \
            + int(self.duiga_box.text()) * prices["duiga_edit"]\
            + int(self.bo_box.text()) * prices["bo_edit"] \
            + int(self.thit_box.text()) * prices["thit_edit"]\
            + int(self.ca_box.text()) * prices["ca_edit"] \
            + int(self.tom_box.text()) * prices["tom_edit"]\
            + int(self.muc_box.text()) * prices["muc_edit"] \
            + int(self.canuong_box.text()) * prices["canuong_edit"]\
            + int(self.xucxich_box.text()) * prices["xucxich_edit"] \
            + int(self.ghe_box.text()) * prices["ghe_edit"]\
            + int(self.xoai_box.text()) * prices["xoai_edit"]\
            + int(self.duahau_box.text()) * prices["duahau_edit"]\
            + int(self.khe_box.text()) * prices["khe_edit"]\
            + int(self.cam_box.text()) * prices["cam_edit"]\
            + int(self.tao_box.text()) * prices["tao_edit"]\
            + int(self.dao_box.text()) * prices["dao_edit"]\
            + int(self.dau_box.text()) * prices["dau_edit"]\
            + int(self.man_box.text()) * prices["man_edit"]
        self.thanhtien_box.setText(str(sum))

    def invoice(self):
        prices = {
            "rauma_edit": 15000,
            "nuoccam_edit": 10000,
            "sinhto_edit": 30000,
            "trasua_edit": 15000,
            "soda_edit": 20000,
            "tradao_edit": 25000,
            "tradau_edit": 30000,
            "tangluc_edit": 15000,
            "trachanh_edit": 20000,
            "duiga_edit": 50000,
            "bo_edit": 300000,
            "thit_edit": 200000,
            "ca_edit": 90000,
            "tom_edit": 20000,
            "muc_edit": 500000,
            "canuong_edit": 150000,
            "xucxich_edit": 170000,
            "ghe_edit": 200000,
            "xoai_edit": 20000,
            "duahau_edit": 30000,
            "khe_edit": 10000,
            "cam_edit": 20000,
            "tao_edit": 15000,
            "dao_edit": 20000,
            "dau_edit": 50000,
            "man_edit": 20000,
        } 
        sum = (False)\
            + int(self.rauma_box.text()) * prices["rauma_edit"] \
            + int(self.nuocam_box.text()) * prices["nuoccam_edit"]\
            + int(self.sinhto_box.text()) * prices["sinhto_edit"] \
            + int(self.trasua_box.text()) * prices["trasua_edit"]\
            + int(self.soda_box.text()) * prices["soda_edit"] \
            + int(self.tradao_box.text()) * prices["tradao_edit"]\
            + int(self.tradau_box.text()) * prices["tradau_edit"] \
            + int(self.tangluc_box.text()) * prices["tangluc_edit"]\
            + int(self.trachanh_box.text()) * prices["trachanh_edit"] \
            + int(self.duiga_box.text()) * prices["duiga_edit"]\
            + int(self.bo_box.text()) * prices["bo_edit"] \
            + int(self.thit_box.text()) * prices["thit_edit"]\
            + int(self.ca_box.text()) * prices["ca_edit"] \
            + int(self.tom_box.text()) * prices["tom_edit"]\
            + int(self.muc_box.text()) * prices["muc_edit"] \
            + int(self.canuong_box.text()) * prices["canuong_edit"]\
            + int(self.xucxich_box.text()) * prices["xucxich_edit"] \
            + int(self.ghe_box.text()) * prices["ghe_edit"]\
            + int(self.xoai_box.text()) * prices["xoai_edit"]\
            + int(self.duahau_box.text()) * prices["duahau_edit"]\
            + int(self.khe_box.text()) * prices["khe_edit"]\
            + int(self.cam_box.text()) * prices["cam_edit"]\
            + int(self.tao_box.text()) * prices["tao_edit"]\
            + int(self.dao_box.text()) * prices["dao_edit"]\
            + int(self.dau_box.text()) * prices["dau_edit"]\
            + int(self.man_box.text()) * prices["man_edit"]
        self.thanhtien_box.setText(str(sum))
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("- Chào bạn  {} !                                                ".format(self.full_name_1.text()))
        msg.setInformativeText("- Tổng chi phí là {} vnđ                             ".format(str(sum)))
        msg.setWindowTitle("Chi phí ngày : {} ".format(self.date_buy.text()))
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
